export const TOPIC_REQUEST = 'TOPIC_REQUEST'
export const TOPIC_SUCCESS = 'TOPIC_SUCCESS'
export const TOPIC_FAIL = 'TOPIC_FAIL'

export const QUESTION_REQUEST = 'QUESTION_REQUEST'
export const QUESTION_SUCCESS = 'QUESTION_SUCCESS'
export const QUESTION_FAIL = 'QUESTION_FAIL'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'